# -*- mode: python ; coding: utf-8 -*-

import os

project_dir = os.path.dirname(os.path.abspath(SPECPATH))

a = Analysis(
    ['speech_recognition_app.py'],
    pathex=[project_dir],
    binaries=[],
    datas=[
        ('config.json', '.'),
        ('whisper_model', 'whisper_model'),
    ],
    hiddenimports=[
        'speech_recognition',
        'tkinter',
        'tkinter.ttk',
        'pyaudio',
        'pyautogui',
        'pyperclip',
        'pystray',
        'pystray._util',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'winsound',
        'queue',
        'threading',
        'json',
        'ctypes',
        'numpy',
        'faster_whisper',
        'ctranslate2',
        'yaml',
        'tqdm',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude GPU/accelerator backends (we only need CPU)
        'torch.cuda',
        'torch.cuda.amp',
        'torch.backends.cuda',
        'torch.backends.cudnn',
        'torch.backends.mps',
        'torch.backends.miopen',
        'torch.backends.xpu',
        'torch.xpu',
        'torch.mps',
        'torch.mtia',
        'torch.accelerator',
        # Exclude distributed training
        'torch.distributed',
        'torch.distributed.tensor',
        'torch.distributed.rpc',
        'torch.distributed.fsdp',
        'torch.distributed.pipelining',
        'torch.distributed.elastic',
        'torch.distributed.checkpoint',
        'torch.distributed.algorithms',
        'torch.distributed.nn',
        # Exclude ONNX / export
        'torch.onnx',
        'torch.export',
        'torch._export',
        # Exclude quantization / pruning
        'torch.quantization',
        'torch.ao',
        'torch.nn.quantized',
        'torch.nn.qat',
        # Exclude FX / JIT / compiler
        'torch.fx',
        'torch.jit',
        'torch.compiler',
        'torch._inductor',
        'torch._dynamo',
        'torch._functorch',
        'functorch',
        # Exclude testing
        'torch.testing',
        'torch._strobelight',
        # Exclude large external deps we don't need
        'numpy.f2py',
        'numpy.testing',
        'numpy.random',
        'numpy.fft',
        'numpy.linalg',
        'numpy.polynomial',
        'numpy.ma',
        'scipy',
        'sympy',
        'pandas',
        'numba',
        'openpyxl',
        'matplotlib',
        'networkx',
        'fastapi',
        'starlette',
        'tokenizers',
        'huggingface_hub',
        'jinja2',
        'mpmath',
        'xlrd',
        'html5lib',
        'bs4',
        'lxml',
        'cffi',
        'pycparser',
        'llvmlite',
        'onnxruntime',
        'filelock',
        'optree',
        'av',
        'httpx',
        'httpcore',
        'anyio',
        'h11',
        'click',
        'typer',
        'pydantic',
        'pydantic_core',
        'annotated_types',
        'typing_inspection',
        'shellingham',
        'markdown_it',
        'mdurl',
        'rich',
        'certifi',
        'cryptography',
        'idna',
        'urllib3',
        'chardet',
        'charset_normalizer',
        'requests',
        'tzdata',
        'dateutil',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='语音识别',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
